#!/bin/python
import os, sys, time, urllib.request, requests
from colorama import init, Fore
from labtool.console import *

init(autoreset=True)

print ("""

_       _       _              _
| | __ _| |__   | |_ ___   ___ | |
| |/ _` | '_ \  | __/ _ \ / _ \| |
| | (_| | |_) | | || (_) | (_) | |
|_|\__,_|_.__/___\__\___/ \___/|_|
            |_____|


""")

if __name__ == '__main__':
         terminal ()
