#!/bin/python
# Copyright ©2021 - 2022 by Dylan Meca. All rights reserved. 
from labtool.console import *

init(autoreset=True)

print ("""
_       _       _              _
| | __ _| |__   | |_ ___   ___ | |
| |/ _` | '_ \  | __/ _ \ / _ \| |
| | (_| | |_) | | || (_) | (_) | |
|_|\__,_|_.__/___\__\___/ \___/|_|
            |_____|
""")

print ("Homepage: https://github.com/dylan14567/lab_tool")
print ("Use the help command for more information about the commands")

if __name__ == '__main__':
         terminal ()
