#!/bin/python
# Copyright ©2021 - 2022 by Dylan Meca. All rights reserved. 
import os
import sys
import time
from colorama import init, Fore, Style
from libsecurity.interpreter import *

init(autoreset=True)

process = process ()

print ("""

   __     __                        _ __
  / /__ _/ /  ___ ___ ______ ______(_) /___ __
 / / _ `/ _ \(_-</ -_) __/ // / __/ / __/ // /
/_/\_,_/_.__/___/\__/\__/\_,_/_/ /_/\__/\_, /
                                       /___/
""")

print ("Homepage: https://github.com/dylan14567/labsecurity")
print ("Use the help command for more information about the commands")

def terminal ():
         
         while True:
               
               try:
                   user = input ("labsecurity > ")
                   prompt = user.split ()
                   
                   if prompt[0] == 'help':
                        process.command_help (user)
                   elif prompt[0] == 'set':
                        global set
                        global argument
                        global data
                        set = prompt[0]
                        argument = prompt[1]
                        data = prompt[2]
                        command = set + argument + data
                        process.command_set (command)
                   elif prompt[0] == 'use':
                        global data1
                        global use
                        use = prompt[0]
                        data1 = prompt[1]
                        command = use + data1
                        process.command_use (command)
                   elif prompt[0] == 'clear':
                        process.command_clear (user)
                   elif prompt[0] == 'exit':
                        break
                   elif prompt[0] == 'run' or prompt[0] == 'exploit': 
                        process.command_run ()
                   else:
                         print (Style.BRIGHT + Fore.RED + "[*] ERROR, use the help command for more information")

               except ValueError:
                        print (Style.BRIGHT + Fore.RED + "[*] Error, there is a type of error.")
                        sys.exit ()
               except KeyboardInterrupt:
                        print (Style.BRIGHT + Fore.BLUE + "[*] Exiting...")
                        sys.exit ()
               except NameError:
                        print (Style.BRIGHT + Fore.RED + "[*] Error, the command I use is not defined in the program code.")
                        sys.exit ()
               except SyntaxError:
                        print (Style.BRIGHT + Fore.RED + "[*] Error, the code has a syntax error.")
                        sys.exit ()
               except IndexError:
                        print (Style.BRIGHT + Fore.RED + "[*] Error, the command you used is incomplete.")
                        sys.exit ()
               

if __name__ == '__main__':
         terminal ()
